name: issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  print-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Comment Body
        run: echo "The issue body is: ${{ github.event.issue.body }}"