name: Issue Event Logger

# Trigger the workflow on any issue event (created, edited, closed, etc.)
on:
  issues:
    types: [opened, edited, closed] # You can adjust the types you want to listen to

jobs:
  log-issue-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Event Metadata
        run: |
          echo "Issue Event Details:"
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
